-- Migration: create figures storage bucket with image mime types and RLS policies
-- Generated by Cascade on 2025-12-20

-- Create storage bucket for figure images
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'figures',
  'figures',
  true, -- public so that images can be displayed openly in reports
  10485760, -- 10 MB limit
  ARRAY[
    'image/png',
    'image/jpeg',
    'image/gif',
    'image/webp',
    'image/svg+xml'
  ]
);

-- Row-level security policies for figures bucket

-- Allow authenticated users to upload to their own folder (user.id prefix)
CREATE POLICY "Authenticated users can upload figures"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'figures' AND auth.uid()::text = (storage.foldername(name))[1]
  );

-- Anyone (including anon) can view figures since bucket is public
CREATE POLICY "Anyone can view figures"
  ON storage.objects FOR SELECT
  TO public
  USING (
    bucket_id = 'figures'
  );

-- Allow authenticated users to delete images in their own folder
CREATE POLICY "Users can delete their own figures"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'figures' AND auth.uid()::text = (storage.foldername(name))[1]
  );
